services:
  - type: web
    name: docegla
    env: python
    python_version: "3.11"
    build_command: pip install --upgrade pip && pip install -r requirements.txt
    start_command: gunicorn docegla.wsgi:application
    plan: free
    env_vars:
      DJANGO_SETTINGS_MODULE